name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Enable Debug Logging
      run: echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV

    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.16.0'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Clear pnpm cache
      run: pnpm store prune || true

    - name: Install dependencies with verbose output
      run: |
        set -x
        pnpm install --frozen-lockfile --reporter=ndjson --debug

    - name: Echo Environment Variables
      run: |
        echo "NODE_ENV is $NODE_ENV"
        echo "Node.js version: $(node -v)"
        echo "PNPM version: $(pnpm -v)"

    - name: Build website with verbose output
      run: |
        set -x
        pnpm run build --verbose

    - name: Upload Build Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: build # or your actual build output directory

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
